-- Insert Endpoint Registry and Role Permissions
-- This script populates EndpointRegistry with unique endpoints and EndpointRolePermission with role mappings

SET NOCOUNT ON;

-- Define all endpoint data
WITH EndpointData AS (
    -- Documents endpoints
    SELECT 'GET' AS HttpMethod, '/api/documents/' AS Route, 'GetAllDocuments' AS EndpointName, 'Get all documents (filtered by permissions)' AS Description, 'Documents' AS Category, 1 AS IsActive, 'Reader' AS RoleName
    UNION ALL SELECT 'GET', '/api/documents/', 'GetAllDocuments', 'Get all documents (filtered by permissions)', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documents/', 'GetAllDocuments', 'Get all documents (filtered by permissions)', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documents/', 'GetAllDocuments', 'Get all documents (filtered by permissions)', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documents/{id}', 'GetDocumentById', 'Get document by ID', 'Documents', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documents/{id}', 'GetDocumentById', 'Get document by ID', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documents/{id}', 'GetDocumentById', 'Get document by ID', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documents/{id}', 'GetDocumentById', 'Get document by ID', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documents/barcode/{barCode}', 'GetDocumentByBarCode', 'Get document by barcode', 'Documents', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documents/barcode/{barCode}', 'GetDocumentByBarCode', 'Get document by barcode', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documents/barcode/{barCode}', 'GetDocumentByBarCode', 'Get document by barcode', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documents/barcode/{barCode}', 'GetDocumentByBarCode', 'Get document by barcode', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/documents/by-ids', 'GetDocumentsByIds', 'Get documents by list of IDs', 'Documents', 1, 'Reader'
    UNION ALL SELECT 'POST', '/api/documents/by-ids', 'GetDocumentsByIds', 'Get documents by list of IDs', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/documents/by-ids', 'GetDocumentsByIds', 'Get documents by list of IDs', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/documents/by-ids', 'GetDocumentsByIds', 'Get documents by list of IDs', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/documents/', 'CreateDocument', 'Create new document', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/documents/', 'CreateDocument', 'Create new document', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/documents/', 'CreateDocument', 'Create new document', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/documents/{id}', 'UpdateDocument', 'Update document', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'PUT', '/api/documents/{id}', 'UpdateDocument', 'Update document', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'PUT', '/api/documents/{id}', 'UpdateDocument', 'Update document', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/documents/{id}', 'DeleteDocument', 'Delete document', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'DELETE', '/api/documents/{id}', 'DeleteDocument', 'Delete document', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/documents/search', 'SearchDocuments', 'Search documents', 'Documents', 1, 'Reader'
    UNION ALL SELECT 'POST', '/api/documents/search', 'SearchDocuments', 'Search documents', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/documents/search', 'SearchDocuments', 'Search documents', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/documents/search', 'SearchDocuments', 'Search documents', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documents/{id}/stream', 'StreamDocumentFile', 'Stream document file (inline)', 'Documents', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documents/{id}/stream', 'StreamDocumentFile', 'Stream document file (inline)', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documents/{id}/stream', 'StreamDocumentFile', 'Stream document file (inline)', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documents/{id}/stream', 'StreamDocumentFile', 'Stream document file (inline)', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documents/{id}/download', 'DownloadDocumentFile', 'Download document file', 'Documents', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documents/{id}/download', 'DownloadDocumentFile', 'Download document file', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documents/{id}/download', 'DownloadDocumentFile', 'Download document file', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documents/{id}/download', 'DownloadDocumentFile', 'Download document file', 'Documents', 1, 'SuperUser'

    -- CounterParties endpoints
    UNION ALL SELECT 'GET', '/api/counterparties/', 'GetAllCounterParties', 'Get all counter parties', 'CounterParties', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/counterparties/', 'GetAllCounterParties', 'Get all counter parties', 'CounterParties', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/counterparties/', 'GetAllCounterParties', 'Get all counter parties', 'CounterParties', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/counterparties/', 'GetAllCounterParties', 'Get all counter parties', 'CounterParties', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/counterparties/search', 'SearchCounterParties', 'Search counter parties', 'CounterParties', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/counterparties/search', 'SearchCounterParties', 'Search counter parties', 'CounterParties', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/counterparties/search', 'SearchCounterParties', 'Search counter parties', 'CounterParties', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/counterparties/search', 'SearchCounterParties', 'Search counter parties', 'CounterParties', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/counterparties/{id}', 'GetCounterPartyById', 'Get counter party by ID', 'CounterParties', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/counterparties/{id}', 'GetCounterPartyById', 'Get counter party by ID', 'CounterParties', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/counterparties/{id}', 'GetCounterPartyById', 'Get counter party by ID', 'CounterParties', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/counterparties/{id}', 'GetCounterPartyById', 'Get counter party by ID', 'CounterParties', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/counterparties/', 'CreateCounterParty', 'Create counter party', 'CounterParties', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/counterparties/{id}', 'UpdateCounterParty', 'Update counter party', 'CounterParties', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/counterparties/{id}', 'DeleteCounterParty', 'Delete counter party', 'CounterParties', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/counterparties/{id}/usage', 'GetCounterPartyUsage', 'Get counter party usage count', 'CounterParties', 1, 'SuperUser'

    -- UserPermissions endpoints
    UNION ALL SELECT 'GET', '/api/userpermissions/', 'GetAllUserPermissions', 'Get all user permissions', 'UserPermissions', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/userpermissions/', 'GetAllUserPermissions', 'Get all user permissions', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/userpermissions/users', 'GetAllDocuScanUsers', 'Get all DocuScan users', 'UserPermissions', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/userpermissions/users', 'GetAllDocuScanUsers', 'Get all DocuScan users', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/userpermissions/{id}', 'GetUserPermissionById', 'Get user permission by ID', 'UserPermissions', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/userpermissions/{id}', 'GetUserPermissionById', 'Get user permission by ID', 'UserPermissions', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/userpermissions/{id}', 'GetUserPermissionById', 'Get user permission by ID', 'UserPermissions', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/userpermissions/{id}', 'GetUserPermissionById', 'Get user permission by ID', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/userpermissions/user/{userId}', 'GetUserPermissionsByUserId', 'Get user permissions by user ID', 'UserPermissions', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/userpermissions/user/{userId}', 'GetUserPermissionsByUserId', 'Get user permissions by user ID', 'UserPermissions', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/userpermissions/user/{userId}', 'GetUserPermissionsByUserId', 'Get user permissions by user ID', 'UserPermissions', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/userpermissions/user/{userId}', 'GetUserPermissionsByUserId', 'Get user permissions by user ID', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/userpermissions/me', 'GetMyPermissions', 'Get current user permissions', 'UserPermissions', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/userpermissions/me', 'GetMyPermissions', 'Get current user permissions', 'UserPermissions', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/userpermissions/me', 'GetMyPermissions', 'Get current user permissions', 'UserPermissions', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/userpermissions/me', 'GetMyPermissions', 'Get current user permissions', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/userpermissions/', 'CreateUserPermission', 'Create user permission', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/userpermissions/{id}', 'UpdateUserPermission', 'Update user permission', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/userpermissions/{id}', 'DeleteUserPermission', 'Delete user permission', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/userpermissions/user/{userId}', 'DeleteDocuScanUser', 'Delete DocuScan user', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/userpermissions/user', 'CreateDocuScanUser', 'Create DocuScan user', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/userpermissions/user/{userId}', 'UpdateDocuScanUser', 'Update DocuScan user', 'UserPermissions', 1, 'SuperUser'

    -- Configuration endpoints
    UNION ALL SELECT 'GET', '/api/configuration/email-recipients', 'GetAllEmailRecipientGroups', 'Get all email recipient groups', 'Configuration', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/configuration/email-recipients', 'GetAllEmailRecipientGroups', 'Get all email recipient groups', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/configuration/email-recipients/{groupKey}', 'GetEmailRecipientGroup', 'Get email recipient group', 'Configuration', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/configuration/email-recipients/{groupKey}', 'GetEmailRecipientGroup', 'Get email recipient group', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/configuration/email-recipients/{groupKey}', 'UpdateEmailRecipientGroup', 'Update email recipient group', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/configuration/email-templates', 'GetAllEmailTemplates', 'Get all email templates', 'Configuration', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/configuration/email-templates', 'GetAllEmailTemplates', 'Get all email templates', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/configuration/email-templates/{key}', 'GetEmailTemplateByKey', 'Get email template by key', 'Configuration', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/configuration/email-templates/{key}', 'GetEmailTemplateByKey', 'Get email template by key', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/configuration/email-templates', 'CreateEmailTemplate', 'Create email template', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/configuration/email-templates/{id}', 'UpdateEmailTemplate', 'Update email template', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/configuration/email-templates/{id}', 'DeactivateEmailTemplate', 'Deactivate email template', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/configuration/sections', 'GetConfigurationSections', 'Get configuration sections', 'Configuration', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/configuration/sections', 'GetConfigurationSections', 'Get configuration sections', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/configuration/{section}/{key}', 'GetConfiguration', 'Get configuration value', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/configuration/{section}/{key}', 'SetConfiguration', 'Set configuration value', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/configuration/smtp', 'UpdateSmtpConfiguration', 'Update SMTP configuration', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/configuration/test-smtp', 'TestSmtpConnection', 'Test SMTP connection', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/configuration/reload', 'ReloadConfigurationCache', 'Reload configuration cache', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/configuration/migrate', 'MigrateConfiguration', 'Migrate configuration', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/configuration/email-templates/preview', 'PreviewEmailTemplate', 'Preview email template', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/configuration/email-templates/placeholders', 'GetEmailTemplatePlaceholders', 'Get email template placeholders', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/configuration/email-templates/diagnostic/DocumentAttachment', 'DiagnoseDocumentAttachmentTemplate', 'Diagnose document attachment template', 'Configuration', 1, 'SuperUser'

    -- LogViewer endpoints
    UNION ALL SELECT 'POST', '/api/logs/search', 'SearchLogs', 'Search logs', 'LogViewer', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/logs/search', 'SearchLogs', 'Search logs', 'LogViewer', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/logs/export', 'ExportLogs', 'Export logs', 'LogViewer', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/logs/export', 'ExportLogs', 'Export logs', 'LogViewer', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/logs/dates', 'GetLogDates', 'Get log dates', 'LogViewer', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/logs/dates', 'GetLogDates', 'Get log dates', 'LogViewer', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/logs/sources', 'GetLogSources', 'Get log sources', 'LogViewer', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/logs/sources', 'GetLogSources', 'Get log sources', 'LogViewer', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/logs/statistics', 'GetLogStatistics', 'Get log statistics', 'LogViewer', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/logs/statistics', 'GetLogStatistics', 'Get log statistics', 'LogViewer', 1, 'SuperUser'

    -- ScannedFiles endpoints
    UNION ALL SELECT 'GET', '/api/scannedfiles/', 'GetAllScannedFiles', 'Get all scanned files', 'ScannedFiles', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/scannedfiles/', 'GetAllScannedFiles', 'Get all scanned files', 'ScannedFiles', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/scannedfiles/', 'GetAllScannedFiles', 'Get all scanned files', 'ScannedFiles', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}', 'GetScannedFileByName', 'Get scanned file by name', 'ScannedFiles', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}', 'GetScannedFileByName', 'Get scanned file by name', 'ScannedFiles', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}', 'GetScannedFileByName', 'Get scanned file by name', 'ScannedFiles', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/content', 'GetScannedFileContent', 'Get scanned file content', 'ScannedFiles', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/content', 'GetScannedFileContent', 'Get scanned file content', 'ScannedFiles', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/content', 'GetScannedFileContent', 'Get scanned file content', 'ScannedFiles', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/exists', 'CheckScannedFileExists', 'Check if scanned file exists', 'ScannedFiles', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/exists', 'CheckScannedFileExists', 'Check if scanned file exists', 'ScannedFiles', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/exists', 'CheckScannedFileExists', 'Check if scanned file exists', 'ScannedFiles', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/stream', 'GetScannedFileStream', 'Stream scanned file', 'ScannedFiles', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/stream', 'GetScannedFileStream', 'Stream scanned file', 'ScannedFiles', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/stream', 'GetScannedFileStream', 'Stream scanned file', 'ScannedFiles', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/scannedfiles/{fileName}', 'DeleteScannedFile', 'Delete scanned file', 'ScannedFiles', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/scannedfiles/{fileName}', 'DeleteScannedFile', 'Delete scanned file', 'ScannedFiles', 1, 'ADAdmin'
    UNION ALL SELECT 'DELETE', '/api/scannedfiles/{fileName}', 'DeleteScannedFile', 'Delete scanned file', 'ScannedFiles', 1, 'Publisher'

    -- ActionReminders endpoints
    UNION ALL SELECT 'GET', '/api/action-reminders/', 'GetDueActions', 'Get due actions', 'ActionReminders', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/action-reminders/', 'GetDueActions', 'Get due actions', 'ActionReminders', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/action-reminders/', 'GetDueActions', 'Get due actions', 'ActionReminders', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/action-reminders/count', 'GetDueActionsCount', 'Get due actions count', 'ActionReminders', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/action-reminders/count', 'GetDueActionsCount', 'Get due actions count', 'ActionReminders', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/action-reminders/count', 'GetDueActionsCount', 'Get due actions count', 'ActionReminders', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/action-reminders/date/{date}', 'GetActionsDueOnDate', 'Get actions due on date', 'ActionReminders', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/action-reminders/date/{date}', 'GetActionsDueOnDate', 'Get actions due on date', 'ActionReminders', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/action-reminders/date/{date}', 'GetActionsDueOnDate', 'Get actions due on date', 'ActionReminders', 1, 'SuperUser'

    -- Reports endpoints
    UNION ALL SELECT 'GET', '/api/reports/barcode-gaps', 'GetBarcodeGapsReport', 'Get barcode gaps report', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/barcode-gaps', 'GetBarcodeGapsReport', 'Get barcode gaps report', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/barcode-gaps', 'GetBarcodeGapsReport', 'Get barcode gaps report', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/duplicate-documents', 'GetDuplicateDocumentsReport', 'Get duplicate documents report', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/duplicate-documents', 'GetDuplicateDocumentsReport', 'Get duplicate documents report', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/duplicate-documents', 'GetDuplicateDocumentsReport', 'Get duplicate documents report', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/unlinked-registrations', 'GetUnlinkedRegistrationsReport', 'Get unlinked registrations report', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/unlinked-registrations', 'GetUnlinkedRegistrationsReport', 'Get unlinked registrations report', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/unlinked-registrations', 'GetUnlinkedRegistrationsReport', 'Get unlinked registrations report', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/scan-copies', 'GetScanCopiesReport', 'Get scan copies report', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/scan-copies', 'GetScanCopiesReport', 'Get scan copies report', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/scan-copies', 'GetScanCopiesReport', 'Get scan copies report', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/suppliers', 'GetSuppliersReport', 'Get suppliers report', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/suppliers', 'GetSuppliersReport', 'Get suppliers report', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/suppliers', 'GetSuppliersReport', 'Get suppliers report', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/all-documents', 'GetAllDocumentsReport', 'Get all documents report', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/all-documents', 'GetAllDocumentsReport', 'Get all documents report', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/all-documents', 'GetAllDocumentsReport', 'Get all documents report', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/barcode-gaps/excel', 'ExportBarcodeGapsToExcel', 'Export barcode gaps to Excel', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/barcode-gaps/excel', 'ExportBarcodeGapsToExcel', 'Export barcode gaps to Excel', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/barcode-gaps/excel', 'ExportBarcodeGapsToExcel', 'Export barcode gaps to Excel', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/duplicate-documents/excel', 'ExportDuplicateDocumentsToExcel', 'Export duplicate documents to Excel', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/duplicate-documents/excel', 'ExportDuplicateDocumentsToExcel', 'Export duplicate documents to Excel', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/duplicate-documents/excel', 'ExportDuplicateDocumentsToExcel', 'Export duplicate documents to Excel', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/unlinked-registrations/excel', 'ExportUnlinkedRegistrationsToExcel', 'Export unlinked registrations to Excel', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/unlinked-registrations/excel', 'ExportUnlinkedRegistrationsToExcel', 'Export unlinked registrations to Excel', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/unlinked-registrations/excel', 'ExportUnlinkedRegistrationsToExcel', 'Export unlinked registrations to Excel', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/scan-copies/excel', 'ExportScanCopiesToExcel', 'Export scan copies to Excel', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/scan-copies/excel', 'ExportScanCopiesToExcel', 'Export scan copies to Excel', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/scan-copies/excel', 'ExportScanCopiesToExcel', 'Export scan copies to Excel', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/suppliers/excel', 'ExportSuppliersToExcel', 'Export suppliers to Excel', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/suppliers/excel', 'ExportSuppliersToExcel', 'Export suppliers to Excel', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/suppliers/excel', 'ExportSuppliersToExcel', 'Export suppliers to Excel', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/all-documents/excel', 'ExportAllDocumentsToExcel', 'Export all documents to Excel', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/all-documents/excel', 'ExportAllDocumentsToExcel', 'Export all documents to Excel', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/all-documents/excel', 'ExportAllDocumentsToExcel', 'Export all documents to Excel', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/reports/documents/search/excel', 'ExportSearchResultsToExcel', 'Export search results to Excel', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/reports/documents/search/excel', 'ExportSearchResultsToExcel', 'Export search results to Excel', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/reports/documents/search/excel', 'ExportSearchResultsToExcel', 'Export search results to Excel', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/reports/documents/selected/excel', 'ExportSelectedDocumentsToExcel', 'Export selected documents to Excel', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/reports/documents/selected/excel', 'ExportSelectedDocumentsToExcel', 'Export selected documents to Excel', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/reports/documents/selected/excel', 'ExportSelectedDocumentsToExcel', 'Export selected documents to Excel', 'Reports', 1, 'SuperUser'

    -- Countries endpoints
    UNION ALL SELECT 'GET', '/api/countries/', 'GetAllCountries', 'Get all countries', 'Countries', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/countries/', 'GetAllCountries', 'Get all countries', 'Countries', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/countries/', 'GetAllCountries', 'Get all countries', 'Countries', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/countries/', 'GetAllCountries', 'Get all countries', 'Countries', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/countries/{code}', 'GetCountryByCode', 'Get country by code', 'Countries', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/countries/{code}', 'GetCountryByCode', 'Get country by code', 'Countries', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/countries/{code}', 'GetCountryByCode', 'Get country by code', 'Countries', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/countries/{code}', 'GetCountryByCode', 'Get country by code', 'Countries', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/countries/', 'CreateCountry', 'Create country', 'Countries', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/countries/{code}', 'UpdateCountry', 'Update country', 'Countries', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/countries/{code}', 'DeleteCountry', 'Delete country', 'Countries', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/countries/{code}/usage', 'GetCountryUsage', 'Get country usage', 'Countries', 1, 'SuperUser'

    -- Currencies endpoints
    UNION ALL SELECT 'GET', '/api/currencies/', 'GetAllCurrencies', 'Get all currencies', 'Currencies', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/currencies/', 'GetAllCurrencies', 'Get all currencies', 'Currencies', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/currencies/', 'GetAllCurrencies', 'Get all currencies', 'Currencies', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/currencies/', 'GetAllCurrencies', 'Get all currencies', 'Currencies', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/currencies/{code}', 'GetCurrencyByCode', 'Get currency by code', 'Currencies', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/currencies/{code}', 'GetCurrencyByCode', 'Get currency by code', 'Currencies', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/currencies/{code}', 'GetCurrencyByCode', 'Get currency by code', 'Currencies', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/currencies/{code}', 'GetCurrencyByCode', 'Get currency by code', 'Currencies', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/currencies/', 'CreateCurrency', 'Create currency', 'Currencies', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/currencies/{code}', 'UpdateCurrency', 'Update currency', 'Currencies', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/currencies/{code}', 'DeleteCurrency', 'Delete currency', 'Currencies', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/currencies/{code}/usage', 'GetCurrencyUsage', 'Get currency usage', 'Currencies', 1, 'SuperUser'

    -- DocumentTypes endpoints
    UNION ALL SELECT 'GET', '/api/documenttypes/', 'GetAllDocumentTypes', 'Get all document types', 'DocumentTypes', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documenttypes/', 'GetAllDocumentTypes', 'Get all document types', 'DocumentTypes', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documenttypes/', 'GetAllDocumentTypes', 'Get all document types', 'DocumentTypes', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documenttypes/', 'GetAllDocumentTypes', 'Get all document types', 'DocumentTypes', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documenttypes/all', 'GetAllDocumentTypesIncludingDisabled', 'Get all document types including disabled', 'DocumentTypes', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documenttypes/all', 'GetAllDocumentTypesIncludingDisabled', 'Get all document types including disabled', 'DocumentTypes', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documenttypes/all', 'GetAllDocumentTypesIncludingDisabled', 'Get all document types including disabled', 'DocumentTypes', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documenttypes/all', 'GetAllDocumentTypesIncludingDisabled', 'Get all document types including disabled', 'DocumentTypes', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documenttypes/{id}', 'GetDocumentTypeById', 'Get document type by ID', 'DocumentTypes', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documenttypes/{id}', 'GetDocumentTypeById', 'Get document type by ID', 'DocumentTypes', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documenttypes/{id}', 'GetDocumentTypeById', 'Get document type by ID', 'DocumentTypes', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documenttypes/{id}', 'GetDocumentTypeById', 'Get document type by ID', 'DocumentTypes', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/documenttypes/', 'CreateDocumentType', 'Create document type', 'DocumentTypes', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/documenttypes/{id}', 'UpdateDocumentType', 'Update document type', 'DocumentTypes', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/documenttypes/{id}', 'DeleteDocumentType', 'Delete document type', 'DocumentTypes', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documenttypes/{id}/usage', 'GetDocumentTypeUsage', 'Get document type usage', 'DocumentTypes', 1, 'SuperUser'

    -- DocumentNames endpoints
    UNION ALL SELECT 'GET', '/api/documentnames/', 'GetAllDocumentNames', 'Get all document names', 'DocumentNames', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documentnames/', 'GetAllDocumentNames', 'Get all document names', 'DocumentNames', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documentnames/', 'GetAllDocumentNames', 'Get all document names', 'DocumentNames', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documentnames/', 'GetAllDocumentNames', 'Get all document names', 'DocumentNames', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documentnames/bytype/{documentTypeId}', 'GetDocumentNamesByType', 'Get document names by type', 'DocumentNames', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documentnames/bytype/{documentTypeId}', 'GetDocumentNamesByType', 'Get document names by type', 'DocumentNames', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documentnames/bytype/{documentTypeId}', 'GetDocumentNamesByType', 'Get document names by type', 'DocumentNames', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documentnames/bytype/{documentTypeId}', 'GetDocumentNamesByType', 'Get document names by type', 'DocumentNames', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documentnames/{id}', 'GetDocumentNameById', 'Get document name by ID', 'DocumentNames', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documentnames/{id}', 'GetDocumentNameById', 'Get document name by ID', 'DocumentNames', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documentnames/{id}', 'GetDocumentNameById', 'Get document name by ID', 'DocumentNames', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documentnames/{id}', 'GetDocumentNameById', 'Get document name by ID', 'DocumentNames', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/documentnames/', 'CreateDocumentName', 'Create document name', 'DocumentNames', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/documentnames/{id}', 'UpdateDocumentName', 'Update document name', 'DocumentNames', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/documentnames/{id}', 'DeleteDocumentName', 'Delete document name', 'DocumentNames', 1, 'SuperUser'

    -- AuditTrail endpoints
    UNION ALL SELECT 'POST', '/api/audittrail/', 'LogAuditTrail', 'Log audit trail entry', 'AuditTrail', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/audittrail/', 'LogAuditTrail', 'Log audit trail entry', 'AuditTrail', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/audittrail/', 'LogAuditTrail', 'Log audit trail entry', 'AuditTrail', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/audittrail/document/{documentId}', 'LogAuditTrailByDocument', 'Log audit trail by document', 'AuditTrail', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/audittrail/document/{documentId}', 'LogAuditTrailByDocument', 'Log audit trail by document', 'AuditTrail', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/audittrail/document/{documentId}', 'LogAuditTrailByDocument', 'Log audit trail by document', 'AuditTrail', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/audittrail/batch', 'LogAuditTrailBatch', 'Log batch audit trail entries', 'AuditTrail', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/audittrail/batch', 'LogAuditTrailBatch', 'Log batch audit trail entries', 'AuditTrail', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/audittrail/batch', 'LogAuditTrailBatch', 'Log batch audit trail entries', 'AuditTrail', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/audittrail/barcode/{barCode}', 'GetAuditTrailByBarCode', 'Get audit trail by barcode', 'AuditTrail', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/audittrail/barcode/{barCode}', 'GetAuditTrailByBarCode', 'Get audit trail by barcode', 'AuditTrail', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/audittrail/barcode/{barCode}', 'GetAuditTrailByBarCode', 'Get audit trail by barcode', 'AuditTrail', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/audittrail/user/{username}', 'GetAuditTrailByUser', 'Get audit trail by user', 'AuditTrail', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/audittrail/user/{username}', 'GetAuditTrailByUser', 'Get audit trail by user', 'AuditTrail', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/audittrail/user/{username}', 'GetAuditTrailByUser', 'Get audit trail by user', 'AuditTrail', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/audittrail/recent', 'GetRecentAuditTrail', 'Get recent audit trail', 'AuditTrail', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/audittrail/recent', 'GetRecentAuditTrail', 'Get recent audit trail', 'AuditTrail', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/audittrail/recent', 'GetRecentAuditTrail', 'Get recent audit trail', 'AuditTrail', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/audittrail/daterange', 'GetAuditTrailByDateRange', 'Get audit trail by date range', 'AuditTrail', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/audittrail/daterange', 'GetAuditTrailByDateRange', 'Get audit trail by date range', 'AuditTrail', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/audittrail/daterange', 'GetAuditTrailByDateRange', 'Get audit trail by date range', 'AuditTrail', 1, 'SuperUser'

    -- Excel endpoints
    UNION ALL SELECT 'POST', '/api/excel/export/documents', 'ExportDocumentsToExcel', 'Export documents to Excel', 'Excel', 1, 'Reader'
    UNION ALL SELECT 'POST', '/api/excel/export/documents', 'ExportDocumentsToExcel', 'Export documents to Excel', 'Excel', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/excel/export/documents', 'ExportDocumentsToExcel', 'Export documents to Excel', 'Excel', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/excel/export/documents', 'ExportDocumentsToExcel', 'Export documents to Excel', 'Excel', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/excel/validate/documents', 'ValidateExportSize', 'Validate export size', 'Excel', 1, 'Reader'
    UNION ALL SELECT 'POST', '/api/excel/validate/documents', 'ValidateExportSize', 'Validate export size', 'Excel', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/excel/validate/documents', 'ValidateExportSize', 'Validate export size', 'Excel', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/excel/validate/documents', 'ValidateExportSize', 'Validate export size', 'Excel', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/excel/metadata/documents', 'GetDocumentExportMetadata', 'Get document export metadata', 'Excel', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/excel/metadata/documents', 'GetDocumentExportMetadata', 'Get document export metadata', 'Excel', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/excel/metadata/documents', 'GetDocumentExportMetadata', 'Get document export metadata', 'Excel', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/excel/metadata/documents', 'GetDocumentExportMetadata', 'Get document export metadata', 'Excel', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/excel/export/by-ids', 'ExportDocumentsByIdsToExcel', 'Export documents by IDs to Excel', 'Excel', 1, 'Reader'
    UNION ALL SELECT 'POST', '/api/excel/export/by-ids', 'ExportDocumentsByIdsToExcel', 'Export documents by IDs to Excel', 'Excel', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/excel/export/by-ids', 'ExportDocumentsByIdsToExcel', 'Export documents by IDs to Excel', 'Excel', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/excel/export/by-ids', 'ExportDocumentsByIdsToExcel', 'Export documents by IDs to Excel', 'Excel', 1, 'SuperUser'

    -- Email endpoints
    UNION ALL SELECT 'POST', '/api/email/send', 'SendEmail', 'Send email', 'Email', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/email/send', 'SendEmail', 'Send email', 'Email', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/email/send', 'SendEmail', 'Send email', 'Email', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/email/send-with-attachments', 'SendEmailWithAttachments', 'Send email with attachments', 'Email', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/email/send-with-attachments', 'SendEmailWithAttachments', 'Send email with attachments', 'Email', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/email/send-with-attachments', 'SendEmailWithAttachments', 'Send email with attachments', 'Email', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/email/send-with-links', 'SendEmailWithLinks', 'Send email with links', 'Email', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/email/send-with-links', 'SendEmailWithLinks', 'Send email with links', 'Email', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/email/send-with-links', 'SendEmailWithLinks', 'Send email with links', 'Email', 1, 'SuperUser'

    -- UserIdentity endpoints
    UNION ALL SELECT 'GET', '/api/user/identity', 'GetUserIdentity', 'Get user identity', 'UserIdentity', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/user/identity', 'GetUserIdentity', 'Get user identity', 'UserIdentity', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/user/identity', 'GetUserIdentity', 'Get user identity', 'UserIdentity', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/user/identity', 'GetUserIdentity', 'Get user identity', 'UserIdentity', 1, 'SuperUser'

    -- Endpoint Authorization endpoints
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/endpoints', 'GetAllEndpoints', 'Get all endpoints with their role permissions', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/endpoints/{id}', 'GetEndpointById', 'Get specific endpoint by ID', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/endpoints/{id}/roles', 'GetEndpointRoles', 'Get roles that have access to a specific endpoint', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/endpoint-authorization/endpoints/{id}/roles', 'UpdateEndpointRoles', 'Update roles for a specific endpoint', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/roles', 'GetAvailableRoles', 'Get all available role names', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/audit', 'GetPermissionAuditLog', 'Get audit log for permission changes', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/endpoint-authorization/cache/invalidate', 'InvalidateAuthorizationCache', 'Invalidate the authorization cache', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/endpoint-authorization/sync', 'SyncEndpointsFromCode', 'Sync endpoints from code to database', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/check', 'CheckEndpointAccess', 'Check if current user has access to a specific endpoint', 'Endpoint Authorization', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/check', 'CheckEndpointAccess', 'Check if current user has access to a specific endpoint', 'Endpoint Authorization', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/check', 'CheckEndpointAccess', 'Check if current user has access to a specific endpoint', 'Endpoint Authorization', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/check', 'CheckEndpointAccess', 'Check if current user has access to a specific endpoint', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/endpoint-authorization/validate', 'ValidatePermissionChange', 'Validate a permission change before applying it', 'Endpoint Authorization', 1, 'SuperUser'

    -- User Permissions batch endpoint
    UNION ALL SELECT 'POST', '/api/userpermissions/user/{userId}/batch-document-types', 'BatchUpdateDocumentTypePermissions', 'Batch update document type permissions for a user', 'User Permissions', 1, 'SuperUser'
)
-- Step 1: Insert unique endpoints into EndpointRegistry
MERGE INTO [dbo].[EndpointRegistry] AS target
USING (
    SELECT DISTINCT
        HttpMethod,
        Route,
        EndpointName,
        Description,
        Category,
        IsActive
    FROM EndpointData
) AS source
ON target.HttpMethod = source.HttpMethod AND target.Route = source.Route
WHEN NOT MATCHED THEN
    INSERT (HttpMethod, Route, EndpointName, Description, Category, IsActive, CreatedOn)
    VALUES (source.HttpMethod, source.Route, source.EndpointName, source.Description, source.Category, source.IsActive, GETDATE())
WHEN MATCHED THEN
    UPDATE SET
        EndpointName = source.EndpointName,
        Description = source.Description,
        Category = source.Category,
        IsActive = source.IsActive,
        ModifiedOn = GETDATE();

-- Step 2: Insert role permissions into EndpointRolePermission
WITH EndpointData AS (
    -- Documents endpoints
    SELECT 'GET' AS HttpMethod, '/api/documents/' AS Route, 'GetAllDocuments' AS EndpointName, 'Get all documents (filtered by permissions)' AS Description, 'Documents' AS Category, 1 AS IsActive, 'Reader' AS RoleName
    UNION ALL SELECT 'GET', '/api/documents/', 'GetAllDocuments', 'Get all documents (filtered by permissions)', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documents/', 'GetAllDocuments', 'Get all documents (filtered by permissions)', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documents/', 'GetAllDocuments', 'Get all documents (filtered by permissions)', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documents/{id}', 'GetDocumentById', 'Get document by ID', 'Documents', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documents/{id}', 'GetDocumentById', 'Get document by ID', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documents/{id}', 'GetDocumentById', 'Get document by ID', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documents/{id}', 'GetDocumentById', 'Get document by ID', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documents/barcode/{barCode}', 'GetDocumentByBarCode', 'Get document by barcode', 'Documents', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documents/barcode/{barCode}', 'GetDocumentByBarCode', 'Get document by barcode', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documents/barcode/{barCode}', 'GetDocumentByBarCode', 'Get document by barcode', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documents/barcode/{barCode}', 'GetDocumentByBarCode', 'Get document by barcode', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/documents/by-ids', 'GetDocumentsByIds', 'Get documents by list of IDs', 'Documents', 1, 'Reader'
    UNION ALL SELECT 'POST', '/api/documents/by-ids', 'GetDocumentsByIds', 'Get documents by list of IDs', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/documents/by-ids', 'GetDocumentsByIds', 'Get documents by list of IDs', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/documents/by-ids', 'GetDocumentsByIds', 'Get documents by list of IDs', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/documents/', 'CreateDocument', 'Create new document', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/documents/', 'CreateDocument', 'Create new document', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/documents/', 'CreateDocument', 'Create new document', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/documents/{id}', 'UpdateDocument', 'Update document', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'PUT', '/api/documents/{id}', 'UpdateDocument', 'Update document', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'PUT', '/api/documents/{id}', 'UpdateDocument', 'Update document', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/documents/{id}', 'DeleteDocument', 'Delete document', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'DELETE', '/api/documents/{id}', 'DeleteDocument', 'Delete document', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/documents/search', 'SearchDocuments', 'Search documents', 'Documents', 1, 'Reader'
    UNION ALL SELECT 'POST', '/api/documents/search', 'SearchDocuments', 'Search documents', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/documents/search', 'SearchDocuments', 'Search documents', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/documents/search', 'SearchDocuments', 'Search documents', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documents/{id}/stream', 'StreamDocumentFile', 'Stream document file (inline)', 'Documents', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documents/{id}/stream', 'StreamDocumentFile', 'Stream document file (inline)', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documents/{id}/stream', 'StreamDocumentFile', 'Stream document file (inline)', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documents/{id}/stream', 'StreamDocumentFile', 'Stream document file (inline)', 'Documents', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documents/{id}/download', 'DownloadDocumentFile', 'Download document file', 'Documents', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documents/{id}/download', 'DownloadDocumentFile', 'Download document file', 'Documents', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documents/{id}/download', 'DownloadDocumentFile', 'Download document file', 'Documents', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documents/{id}/download', 'DownloadDocumentFile', 'Download document file', 'Documents', 1, 'SuperUser'

    -- CounterParties endpoints
    UNION ALL SELECT 'GET', '/api/counterparties/', 'GetAllCounterParties', 'Get all counter parties', 'CounterParties', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/counterparties/', 'GetAllCounterParties', 'Get all counter parties', 'CounterParties', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/counterparties/', 'GetAllCounterParties', 'Get all counter parties', 'CounterParties', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/counterparties/', 'GetAllCounterParties', 'Get all counter parties', 'CounterParties', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/counterparties/search', 'SearchCounterParties', 'Search counter parties', 'CounterParties', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/counterparties/search', 'SearchCounterParties', 'Search counter parties', 'CounterParties', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/counterparties/search', 'SearchCounterParties', 'Search counter parties', 'CounterParties', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/counterparties/search', 'SearchCounterParties', 'Search counter parties', 'CounterParties', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/counterparties/{id}', 'GetCounterPartyById', 'Get counter party by ID', 'CounterParties', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/counterparties/{id}', 'GetCounterPartyById', 'Get counter party by ID', 'CounterParties', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/counterparties/{id}', 'GetCounterPartyById', 'Get counter party by ID', 'CounterParties', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/counterparties/{id}', 'GetCounterPartyById', 'Get counter party by ID', 'CounterParties', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/counterparties/', 'CreateCounterParty', 'Create counter party', 'CounterParties', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/counterparties/{id}', 'UpdateCounterParty', 'Update counter party', 'CounterParties', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/counterparties/{id}', 'DeleteCounterParty', 'Delete counter party', 'CounterParties', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/counterparties/{id}/usage', 'GetCounterPartyUsage', 'Get counter party usage count', 'CounterParties', 1, 'SuperUser'

    -- UserPermissions endpoints
    UNION ALL SELECT 'GET', '/api/userpermissions/', 'GetAllUserPermissions', 'Get all user permissions', 'UserPermissions', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/userpermissions/', 'GetAllUserPermissions', 'Get all user permissions', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/userpermissions/users', 'GetAllDocuScanUsers', 'Get all DocuScan users', 'UserPermissions', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/userpermissions/users', 'GetAllDocuScanUsers', 'Get all DocuScan users', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/userpermissions/{id}', 'GetUserPermissionById', 'Get user permission by ID', 'UserPermissions', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/userpermissions/{id}', 'GetUserPermissionById', 'Get user permission by ID', 'UserPermissions', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/userpermissions/{id}', 'GetUserPermissionById', 'Get user permission by ID', 'UserPermissions', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/userpermissions/{id}', 'GetUserPermissionById', 'Get user permission by ID', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/userpermissions/user/{userId}', 'GetUserPermissionsByUserId', 'Get user permissions by user ID', 'UserPermissions', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/userpermissions/user/{userId}', 'GetUserPermissionsByUserId', 'Get user permissions by user ID', 'UserPermissions', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/userpermissions/user/{userId}', 'GetUserPermissionsByUserId', 'Get user permissions by user ID', 'UserPermissions', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/userpermissions/user/{userId}', 'GetUserPermissionsByUserId', 'Get user permissions by user ID', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/userpermissions/me', 'GetMyPermissions', 'Get current user permissions', 'UserPermissions', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/userpermissions/me', 'GetMyPermissions', 'Get current user permissions', 'UserPermissions', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/userpermissions/me', 'GetMyPermissions', 'Get current user permissions', 'UserPermissions', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/userpermissions/me', 'GetMyPermissions', 'Get current user permissions', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/userpermissions/', 'CreateUserPermission', 'Create user permission', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/userpermissions/{id}', 'UpdateUserPermission', 'Update user permission', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/userpermissions/{id}', 'DeleteUserPermission', 'Delete user permission', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/userpermissions/user/{userId}', 'DeleteDocuScanUser', 'Delete DocuScan user', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/userpermissions/user', 'CreateDocuScanUser', 'Create DocuScan user', 'UserPermissions', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/userpermissions/user/{userId}', 'UpdateDocuScanUser', 'Update DocuScan user', 'UserPermissions', 1, 'SuperUser'

    -- Configuration endpoints
    UNION ALL SELECT 'GET', '/api/configuration/email-recipients', 'GetAllEmailRecipientGroups', 'Get all email recipient groups', 'Configuration', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/configuration/email-recipients', 'GetAllEmailRecipientGroups', 'Get all email recipient groups', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/configuration/email-recipients/{groupKey}', 'GetEmailRecipientGroup', 'Get email recipient group', 'Configuration', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/configuration/email-recipients/{groupKey}', 'GetEmailRecipientGroup', 'Get email recipient group', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/configuration/email-recipients/{groupKey}', 'UpdateEmailRecipientGroup', 'Update email recipient group', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/configuration/email-templates', 'GetAllEmailTemplates', 'Get all email templates', 'Configuration', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/configuration/email-templates', 'GetAllEmailTemplates', 'Get all email templates', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/configuration/email-templates/{key}', 'GetEmailTemplateByKey', 'Get email template by key', 'Configuration', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/configuration/email-templates/{key}', 'GetEmailTemplateByKey', 'Get email template by key', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/configuration/email-templates', 'CreateEmailTemplate', 'Create email template', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/configuration/email-templates/{id}', 'UpdateEmailTemplate', 'Update email template', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/configuration/email-templates/{id}', 'DeactivateEmailTemplate', 'Deactivate email template', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/configuration/sections', 'GetConfigurationSections', 'Get configuration sections', 'Configuration', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/configuration/sections', 'GetConfigurationSections', 'Get configuration sections', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/configuration/{section}/{key}', 'GetConfiguration', 'Get configuration value', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/configuration/{section}/{key}', 'SetConfiguration', 'Set configuration value', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/configuration/smtp', 'UpdateSmtpConfiguration', 'Update SMTP configuration', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/configuration/test-smtp', 'TestSmtpConnection', 'Test SMTP connection', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/configuration/reload', 'ReloadConfigurationCache', 'Reload configuration cache', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/configuration/migrate', 'MigrateConfiguration', 'Migrate configuration', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/configuration/email-templates/preview', 'PreviewEmailTemplate', 'Preview email template', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/configuration/email-templates/placeholders', 'GetEmailTemplatePlaceholders', 'Get email template placeholders', 'Configuration', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/configuration/email-templates/diagnostic/DocumentAttachment', 'DiagnoseDocumentAttachmentTemplate', 'Diagnose document attachment template', 'Configuration', 1, 'SuperUser'

    -- LogViewer endpoints
    UNION ALL SELECT 'POST', '/api/logs/search', 'SearchLogs', 'Search logs', 'LogViewer', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/logs/search', 'SearchLogs', 'Search logs', 'LogViewer', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/logs/export', 'ExportLogs', 'Export logs', 'LogViewer', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/logs/export', 'ExportLogs', 'Export logs', 'LogViewer', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/logs/dates', 'GetLogDates', 'Get log dates', 'LogViewer', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/logs/dates', 'GetLogDates', 'Get log dates', 'LogViewer', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/logs/sources', 'GetLogSources', 'Get log sources', 'LogViewer', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/logs/sources', 'GetLogSources', 'Get log sources', 'LogViewer', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/logs/statistics', 'GetLogStatistics', 'Get log statistics', 'LogViewer', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/logs/statistics', 'GetLogStatistics', 'Get log statistics', 'LogViewer', 1, 'SuperUser'

    -- ScannedFiles endpoints
    UNION ALL SELECT 'GET', '/api/scannedfiles/', 'GetAllScannedFiles', 'Get all scanned files', 'ScannedFiles', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/scannedfiles/', 'GetAllScannedFiles', 'Get all scanned files', 'ScannedFiles', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/scannedfiles/', 'GetAllScannedFiles', 'Get all scanned files', 'ScannedFiles', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}', 'GetScannedFileByName', 'Get scanned file by name', 'ScannedFiles', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}', 'GetScannedFileByName', 'Get scanned file by name', 'ScannedFiles', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}', 'GetScannedFileByName', 'Get scanned file by name', 'ScannedFiles', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/content', 'GetScannedFileContent', 'Get scanned file content', 'ScannedFiles', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/content', 'GetScannedFileContent', 'Get scanned file content', 'ScannedFiles', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/content', 'GetScannedFileContent', 'Get scanned file content', 'ScannedFiles', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/exists', 'CheckScannedFileExists', 'Check if scanned file exists', 'ScannedFiles', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/exists', 'CheckScannedFileExists', 'Check if scanned file exists', 'ScannedFiles', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/exists', 'CheckScannedFileExists', 'Check if scanned file exists', 'ScannedFiles', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/stream', 'GetScannedFileStream', 'Stream scanned file', 'ScannedFiles', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/stream', 'GetScannedFileStream', 'Stream scanned file', 'ScannedFiles', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/scannedfiles/{fileName}/stream', 'GetScannedFileStream', 'Stream scanned file', 'ScannedFiles', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/scannedfiles/{fileName}', 'DeleteScannedFile', 'Delete scanned file', 'ScannedFiles', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/scannedfiles/{fileName}', 'DeleteScannedFile', 'Delete scanned file', 'ScannedFiles', 1, 'ADAdmin'
    UNION ALL SELECT 'DELETE', '/api/scannedfiles/{fileName}', 'DeleteScannedFile', 'Delete scanned file', 'ScannedFiles', 1, 'Publisher'

    -- ActionReminders endpoints
    UNION ALL SELECT 'GET', '/api/action-reminders/', 'GetDueActions', 'Get due actions', 'ActionReminders', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/action-reminders/', 'GetDueActions', 'Get due actions', 'ActionReminders', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/action-reminders/', 'GetDueActions', 'Get due actions', 'ActionReminders', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/action-reminders/count', 'GetDueActionsCount', 'Get due actions count', 'ActionReminders', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/action-reminders/count', 'GetDueActionsCount', 'Get due actions count', 'ActionReminders', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/action-reminders/count', 'GetDueActionsCount', 'Get due actions count', 'ActionReminders', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/action-reminders/date/{date}', 'GetActionsDueOnDate', 'Get actions due on date', 'ActionReminders', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/action-reminders/date/{date}', 'GetActionsDueOnDate', 'Get actions due on date', 'ActionReminders', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/action-reminders/date/{date}', 'GetActionsDueOnDate', 'Get actions due on date', 'ActionReminders', 1, 'SuperUser'

    -- Reports endpoints
    UNION ALL SELECT 'GET', '/api/reports/barcode-gaps', 'GetBarcodeGapsReport', 'Get barcode gaps report', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/barcode-gaps', 'GetBarcodeGapsReport', 'Get barcode gaps report', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/barcode-gaps', 'GetBarcodeGapsReport', 'Get barcode gaps report', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/duplicate-documents', 'GetDuplicateDocumentsReport', 'Get duplicate documents report', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/duplicate-documents', 'GetDuplicateDocumentsReport', 'Get duplicate documents report', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/duplicate-documents', 'GetDuplicateDocumentsReport', 'Get duplicate documents report', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/unlinked-registrations', 'GetUnlinkedRegistrationsReport', 'Get unlinked registrations report', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/unlinked-registrations', 'GetUnlinkedRegistrationsReport', 'Get unlinked registrations report', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/unlinked-registrations', 'GetUnlinkedRegistrationsReport', 'Get unlinked registrations report', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/scan-copies', 'GetScanCopiesReport', 'Get scan copies report', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/scan-copies', 'GetScanCopiesReport', 'Get scan copies report', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/scan-copies', 'GetScanCopiesReport', 'Get scan copies report', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/suppliers', 'GetSuppliersReport', 'Get suppliers report', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/suppliers', 'GetSuppliersReport', 'Get suppliers report', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/suppliers', 'GetSuppliersReport', 'Get suppliers report', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/all-documents', 'GetAllDocumentsReport', 'Get all documents report', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/all-documents', 'GetAllDocumentsReport', 'Get all documents report', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/all-documents', 'GetAllDocumentsReport', 'Get all documents report', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/barcode-gaps/excel', 'ExportBarcodeGapsToExcel', 'Export barcode gaps to Excel', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/barcode-gaps/excel', 'ExportBarcodeGapsToExcel', 'Export barcode gaps to Excel', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/barcode-gaps/excel', 'ExportBarcodeGapsToExcel', 'Export barcode gaps to Excel', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/duplicate-documents/excel', 'ExportDuplicateDocumentsToExcel', 'Export duplicate documents to Excel', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/duplicate-documents/excel', 'ExportDuplicateDocumentsToExcel', 'Export duplicate documents to Excel', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/duplicate-documents/excel', 'ExportDuplicateDocumentsToExcel', 'Export duplicate documents to Excel', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/unlinked-registrations/excel', 'ExportUnlinkedRegistrationsToExcel', 'Export unlinked registrations to Excel', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/unlinked-registrations/excel', 'ExportUnlinkedRegistrationsToExcel', 'Export unlinked registrations to Excel', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/unlinked-registrations/excel', 'ExportUnlinkedRegistrationsToExcel', 'Export unlinked registrations to Excel', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/scan-copies/excel', 'ExportScanCopiesToExcel', 'Export scan copies to Excel', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/scan-copies/excel', 'ExportScanCopiesToExcel', 'Export scan copies to Excel', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/scan-copies/excel', 'ExportScanCopiesToExcel', 'Export scan copies to Excel', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/suppliers/excel', 'ExportSuppliersToExcel', 'Export suppliers to Excel', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/suppliers/excel', 'ExportSuppliersToExcel', 'Export suppliers to Excel', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/suppliers/excel', 'ExportSuppliersToExcel', 'Export suppliers to Excel', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/reports/all-documents/excel', 'ExportAllDocumentsToExcel', 'Export all documents to Excel', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/reports/all-documents/excel', 'ExportAllDocumentsToExcel', 'Export all documents to Excel', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/reports/all-documents/excel', 'ExportAllDocumentsToExcel', 'Export all documents to Excel', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/reports/documents/search/excel', 'ExportSearchResultsToExcel', 'Export search results to Excel', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/reports/documents/search/excel', 'ExportSearchResultsToExcel', 'Export search results to Excel', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/reports/documents/search/excel', 'ExportSearchResultsToExcel', 'Export search results to Excel', 'Reports', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/reports/documents/selected/excel', 'ExportSelectedDocumentsToExcel', 'Export selected documents to Excel', 'Reports', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/reports/documents/selected/excel', 'ExportSelectedDocumentsToExcel', 'Export selected documents to Excel', 'Reports', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/reports/documents/selected/excel', 'ExportSelectedDocumentsToExcel', 'Export selected documents to Excel', 'Reports', 1, 'SuperUser'

    -- Countries endpoints
    UNION ALL SELECT 'GET', '/api/countries/', 'GetAllCountries', 'Get all countries', 'Countries', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/countries/', 'GetAllCountries', 'Get all countries', 'Countries', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/countries/', 'GetAllCountries', 'Get all countries', 'Countries', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/countries/', 'GetAllCountries', 'Get all countries', 'Countries', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/countries/{code}', 'GetCountryByCode', 'Get country by code', 'Countries', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/countries/{code}', 'GetCountryByCode', 'Get country by code', 'Countries', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/countries/{code}', 'GetCountryByCode', 'Get country by code', 'Countries', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/countries/{code}', 'GetCountryByCode', 'Get country by code', 'Countries', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/countries/', 'CreateCountry', 'Create country', 'Countries', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/countries/{code}', 'UpdateCountry', 'Update country', 'Countries', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/countries/{code}', 'DeleteCountry', 'Delete country', 'Countries', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/countries/{code}/usage', 'GetCountryUsage', 'Get country usage', 'Countries', 1, 'SuperUser'

    -- Currencies endpoints
    UNION ALL SELECT 'GET', '/api/currencies/', 'GetAllCurrencies', 'Get all currencies', 'Currencies', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/currencies/', 'GetAllCurrencies', 'Get all currencies', 'Currencies', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/currencies/', 'GetAllCurrencies', 'Get all currencies', 'Currencies', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/currencies/', 'GetAllCurrencies', 'Get all currencies', 'Currencies', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/currencies/{code}', 'GetCurrencyByCode', 'Get currency by code', 'Currencies', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/currencies/{code}', 'GetCurrencyByCode', 'Get currency by code', 'Currencies', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/currencies/{code}', 'GetCurrencyByCode', 'Get currency by code', 'Currencies', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/currencies/{code}', 'GetCurrencyByCode', 'Get currency by code', 'Currencies', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/currencies/', 'CreateCurrency', 'Create currency', 'Currencies', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/currencies/{code}', 'UpdateCurrency', 'Update currency', 'Currencies', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/currencies/{code}', 'DeleteCurrency', 'Delete currency', 'Currencies', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/currencies/{code}/usage', 'GetCurrencyUsage', 'Get currency usage', 'Currencies', 1, 'SuperUser'

    -- DocumentTypes endpoints
    UNION ALL SELECT 'GET', '/api/documenttypes/', 'GetAllDocumentTypes', 'Get all document types', 'DocumentTypes', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documenttypes/', 'GetAllDocumentTypes', 'Get all document types', 'DocumentTypes', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documenttypes/', 'GetAllDocumentTypes', 'Get all document types', 'DocumentTypes', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documenttypes/', 'GetAllDocumentTypes', 'Get all document types', 'DocumentTypes', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documenttypes/all', 'GetAllDocumentTypesIncludingDisabled', 'Get all document types including disabled', 'DocumentTypes', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documenttypes/all', 'GetAllDocumentTypesIncludingDisabled', 'Get all document types including disabled', 'DocumentTypes', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documenttypes/all', 'GetAllDocumentTypesIncludingDisabled', 'Get all document types including disabled', 'DocumentTypes', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documenttypes/all', 'GetAllDocumentTypesIncludingDisabled', 'Get all document types including disabled', 'DocumentTypes', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documenttypes/{id}', 'GetDocumentTypeById', 'Get document type by ID', 'DocumentTypes', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documenttypes/{id}', 'GetDocumentTypeById', 'Get document type by ID', 'DocumentTypes', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documenttypes/{id}', 'GetDocumentTypeById', 'Get document type by ID', 'DocumentTypes', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documenttypes/{id}', 'GetDocumentTypeById', 'Get document type by ID', 'DocumentTypes', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/documenttypes/', 'CreateDocumentType', 'Create document type', 'DocumentTypes', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/documenttypes/{id}', 'UpdateDocumentType', 'Update document type', 'DocumentTypes', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/documenttypes/{id}', 'DeleteDocumentType', 'Delete document type', 'DocumentTypes', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documenttypes/{id}/usage', 'GetDocumentTypeUsage', 'Get document type usage', 'DocumentTypes', 1, 'SuperUser'

    -- DocumentNames endpoints
    UNION ALL SELECT 'GET', '/api/documentnames/', 'GetAllDocumentNames', 'Get all document names', 'DocumentNames', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documentnames/', 'GetAllDocumentNames', 'Get all document names', 'DocumentNames', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documentnames/', 'GetAllDocumentNames', 'Get all document names', 'DocumentNames', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documentnames/', 'GetAllDocumentNames', 'Get all document names', 'DocumentNames', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documentnames/bytype/{documentTypeId}', 'GetDocumentNamesByType', 'Get document names by type', 'DocumentNames', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documentnames/bytype/{documentTypeId}', 'GetDocumentNamesByType', 'Get document names by type', 'DocumentNames', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documentnames/bytype/{documentTypeId}', 'GetDocumentNamesByType', 'Get document names by type', 'DocumentNames', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documentnames/bytype/{documentTypeId}', 'GetDocumentNamesByType', 'Get document names by type', 'DocumentNames', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/documentnames/{id}', 'GetDocumentNameById', 'Get document name by ID', 'DocumentNames', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/documentnames/{id}', 'GetDocumentNameById', 'Get document name by ID', 'DocumentNames', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/documentnames/{id}', 'GetDocumentNameById', 'Get document name by ID', 'DocumentNames', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/documentnames/{id}', 'GetDocumentNameById', 'Get document name by ID', 'DocumentNames', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/documentnames/', 'CreateDocumentName', 'Create document name', 'DocumentNames', 1, 'SuperUser'
    UNION ALL SELECT 'PUT', '/api/documentnames/{id}', 'UpdateDocumentName', 'Update document name', 'DocumentNames', 1, 'SuperUser'
    UNION ALL SELECT 'DELETE', '/api/documentnames/{id}', 'DeleteDocumentName', 'Delete document name', 'DocumentNames', 1, 'SuperUser'

    -- AuditTrail endpoints
    UNION ALL SELECT 'POST', '/api/audittrail/', 'LogAuditTrail', 'Log audit trail entry', 'AuditTrail', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/audittrail/', 'LogAuditTrail', 'Log audit trail entry', 'AuditTrail', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/audittrail/', 'LogAuditTrail', 'Log audit trail entry', 'AuditTrail', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/audittrail/document/{documentId}', 'LogAuditTrailByDocument', 'Log audit trail by document', 'AuditTrail', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/audittrail/document/{documentId}', 'LogAuditTrailByDocument', 'Log audit trail by document', 'AuditTrail', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/audittrail/document/{documentId}', 'LogAuditTrailByDocument', 'Log audit trail by document', 'AuditTrail', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/audittrail/batch', 'LogAuditTrailBatch', 'Log batch audit trail entries', 'AuditTrail', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/audittrail/batch', 'LogAuditTrailBatch', 'Log batch audit trail entries', 'AuditTrail', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/audittrail/batch', 'LogAuditTrailBatch', 'Log batch audit trail entries', 'AuditTrail', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/audittrail/barcode/{barCode}', 'GetAuditTrailByBarCode', 'Get audit trail by barcode', 'AuditTrail', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/audittrail/barcode/{barCode}', 'GetAuditTrailByBarCode', 'Get audit trail by barcode', 'AuditTrail', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/audittrail/barcode/{barCode}', 'GetAuditTrailByBarCode', 'Get audit trail by barcode', 'AuditTrail', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/audittrail/user/{username}', 'GetAuditTrailByUser', 'Get audit trail by user', 'AuditTrail', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/audittrail/user/{username}', 'GetAuditTrailByUser', 'Get audit trail by user', 'AuditTrail', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/audittrail/user/{username}', 'GetAuditTrailByUser', 'Get audit trail by user', 'AuditTrail', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/audittrail/recent', 'GetRecentAuditTrail', 'Get recent audit trail', 'AuditTrail', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/audittrail/recent', 'GetRecentAuditTrail', 'Get recent audit trail', 'AuditTrail', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/audittrail/recent', 'GetRecentAuditTrail', 'Get recent audit trail', 'AuditTrail', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/audittrail/daterange', 'GetAuditTrailByDateRange', 'Get audit trail by date range', 'AuditTrail', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/audittrail/daterange', 'GetAuditTrailByDateRange', 'Get audit trail by date range', 'AuditTrail', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/audittrail/daterange', 'GetAuditTrailByDateRange', 'Get audit trail by date range', 'AuditTrail', 1, 'SuperUser'

    -- Excel endpoints
    UNION ALL SELECT 'POST', '/api/excel/export/documents', 'ExportDocumentsToExcel', 'Export documents to Excel', 'Excel', 1, 'Reader'
    UNION ALL SELECT 'POST', '/api/excel/export/documents', 'ExportDocumentsToExcel', 'Export documents to Excel', 'Excel', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/excel/export/documents', 'ExportDocumentsToExcel', 'Export documents to Excel', 'Excel', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/excel/export/documents', 'ExportDocumentsToExcel', 'Export documents to Excel', 'Excel', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/excel/validate/documents', 'ValidateExportSize', 'Validate export size', 'Excel', 1, 'Reader'
    UNION ALL SELECT 'POST', '/api/excel/validate/documents', 'ValidateExportSize', 'Validate export size', 'Excel', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/excel/validate/documents', 'ValidateExportSize', 'Validate export size', 'Excel', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/excel/validate/documents', 'ValidateExportSize', 'Validate export size', 'Excel', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/excel/metadata/documents', 'GetDocumentExportMetadata', 'Get document export metadata', 'Excel', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/excel/metadata/documents', 'GetDocumentExportMetadata', 'Get document export metadata', 'Excel', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/excel/metadata/documents', 'GetDocumentExportMetadata', 'Get document export metadata', 'Excel', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/excel/metadata/documents', 'GetDocumentExportMetadata', 'Get document export metadata', 'Excel', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/excel/export/by-ids', 'ExportDocumentsByIdsToExcel', 'Export documents by IDs to Excel', 'Excel', 1, 'Reader'
    UNION ALL SELECT 'POST', '/api/excel/export/by-ids', 'ExportDocumentsByIdsToExcel', 'Export documents by IDs to Excel', 'Excel', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/excel/export/by-ids', 'ExportDocumentsByIdsToExcel', 'Export documents by IDs to Excel', 'Excel', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/excel/export/by-ids', 'ExportDocumentsByIdsToExcel', 'Export documents by IDs to Excel', 'Excel', 1, 'SuperUser'

    -- Email endpoints
    UNION ALL SELECT 'POST', '/api/email/send', 'SendEmail', 'Send email', 'Email', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/email/send', 'SendEmail', 'Send email', 'Email', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/email/send', 'SendEmail', 'Send email', 'Email', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/email/send-with-attachments', 'SendEmailWithAttachments', 'Send email with attachments', 'Email', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/email/send-with-attachments', 'SendEmailWithAttachments', 'Send email with attachments', 'Email', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/email/send-with-attachments', 'SendEmailWithAttachments', 'Send email with attachments', 'Email', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/email/send-with-links', 'SendEmailWithLinks', 'Send email with links', 'Email', 1, 'Publisher'
    UNION ALL SELECT 'POST', '/api/email/send-with-links', 'SendEmailWithLinks', 'Send email with links', 'Email', 1, 'ADAdmin'
    UNION ALL SELECT 'POST', '/api/email/send-with-links', 'SendEmailWithLinks', 'Send email with links', 'Email', 1, 'SuperUser'

    -- UserIdentity endpoints
    UNION ALL SELECT 'GET', '/api/user/identity', 'GetUserIdentity', 'Get user identity', 'UserIdentity', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/user/identity', 'GetUserIdentity', 'Get user identity', 'UserIdentity', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/user/identity', 'GetUserIdentity', 'Get user identity', 'UserIdentity', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/user/identity', 'GetUserIdentity', 'Get user identity', 'UserIdentity', 1, 'SuperUser'

    -- Endpoint Authorization endpoints
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/endpoints', 'GetAllEndpoints', 'Get all endpoints with their role permissions', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/endpoints/{id}', 'GetEndpointById', 'Get specific endpoint by ID', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/endpoints/{id}/roles', 'GetEndpointRoles', 'Get roles that have access to a specific endpoint', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/endpoint-authorization/endpoints/{id}/roles', 'UpdateEndpointRoles', 'Update roles for a specific endpoint', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/roles', 'GetAvailableRoles', 'Get all available role names', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/audit', 'GetPermissionAuditLog', 'Get audit log for permission changes', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/endpoint-authorization/cache/invalidate', 'InvalidateAuthorizationCache', 'Invalidate the authorization cache', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/endpoint-authorization/sync', 'SyncEndpointsFromCode', 'Sync endpoints from code to database', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/check', 'CheckEndpointAccess', 'Check if current user has access to a specific endpoint', 'Endpoint Authorization', 1, 'Reader'
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/check', 'CheckEndpointAccess', 'Check if current user has access to a specific endpoint', 'Endpoint Authorization', 1, 'Publisher'
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/check', 'CheckEndpointAccess', 'Check if current user has access to a specific endpoint', 'Endpoint Authorization', 1, 'ADAdmin'
    UNION ALL SELECT 'GET', '/api/endpoint-authorization/check', 'CheckEndpointAccess', 'Check if current user has access to a specific endpoint', 'Endpoint Authorization', 1, 'SuperUser'
    UNION ALL SELECT 'POST', '/api/endpoint-authorization/validate', 'ValidatePermissionChange', 'Validate a permission change before applying it', 'Endpoint Authorization', 1, 'SuperUser'

    -- User Permissions batch endpoint
    UNION ALL SELECT 'POST', '/api/userpermissions/user/{userId}/batch-document-types', 'BatchUpdateDocumentTypePermissions', 'Batch update document type permissions for a user', 'User Permissions', 1, 'SuperUser'
)
INSERT INTO [dbo].[EndpointRolePermission] (EndpointId, RoleName, CreatedOn)
SELECT
    er.EndpointId,
    ed.RoleName,
    GETDATE()
FROM EndpointData ed
INNER JOIN [dbo].[EndpointRegistry] er
    ON ed.HttpMethod = er.HttpMethod
    AND ed.Route = er.Route
WHERE NOT EXISTS (
    SELECT 1
    FROM [dbo].[EndpointRolePermission] erp
    WHERE erp.EndpointId = er.EndpointId
    AND erp.RoleName = ed.RoleName
);

-- Summary
PRINT 'Endpoint Registry and Role Permissions seeding completed.';

SET NOCOUNT OFF;
