// This file helps IDEs recognize CSnakes-generated code
// The actual implementation will be generated by CSnakes at build time

namespace IkeaDocuScan.PdfTools;

// CSnakes will generate this class from Python/pdf_extractor.py
// Uncomment after first successful build when the class is generated:
// using static PdfExtractor;

// If you get errors about PdfExtractor not existing:
// 1. Build the project: dotnet build
// 2. Check obj/Generated/ folder for generated files
// 3. Look for the actual generated class name
// 4. Update PdfTextExtractor.cs to use the correct name
