// <auto-generated />
using System;
using IkeaDocuScan.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IkeaDocuScan.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104000000_RemoveCounterPartyRelationTables")]
    partial class RemoveCounterPartyRelationTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Model snapshot after removing CounterPartyRelation and CounterPartyRelationType
            // This is intentionally minimal as it's just for the migration
#pragma warning restore 612, 618
        }
    }
}
