// <auto-generated />
using System;
using IkeaDocuScan.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IkeaDocuScan.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251104221107_AddConfigurationTables")]
    partial class AddConfigurationTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.AuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Details")
                        .HasMaxLength(2500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2500)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id")
                        .HasName("PK__AuditTrail__4AB81AF0");

                    b.ToTable("AuditTrail");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.Configuration.EmailRecipient", b =>
                {
                    b.Property<int>("RecipientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipientId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("RecipientId");

                    b.HasIndex("GroupId", "EmailAddress")
                        .IsUnique()
                        .HasDatabaseName("IX_EmailRecipient_Group_Email");

                    b.HasIndex("GroupId", "IsActive")
                        .HasDatabaseName("IX_EmailRecipient_Group_Active");

                    b.ToTable("EmailRecipient", (string)null);
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.Configuration.EmailRecipientGroup", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("GroupId");

                    b.HasIndex("GroupKey")
                        .IsUnique()
                        .HasDatabaseName("IX_EmailRecipientGroup_Key");

                    b.HasIndex("GroupName")
                        .IsUnique()
                        .HasDatabaseName("IX_EmailRecipientGroup_Name");

                    b.ToTable("EmailRecipientGroup", (string)null);
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.Configuration.EmailTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlaceholderDefinitions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlainTextBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TemplateId");

                    b.HasIndex("TemplateKey")
                        .IsUnique()
                        .HasDatabaseName("IX_EmailTemplate_Key");

                    b.HasIndex("TemplateName")
                        .IsUnique()
                        .HasDatabaseName("IX_EmailTemplate_Name");

                    b.HasIndex("TemplateKey", "IsActive")
                        .HasDatabaseName("IX_EmailTemplate_Key_Active");

                    b.ToTable("EmailTemplate", (string)null);
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.Configuration.SystemConfiguration", b =>
                {
                    b.Property<int>("ConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigurationId"));

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConfigSection")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOverride")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ConfigurationId");

                    b.HasIndex("ConfigKey")
                        .IsUnique()
                        .HasDatabaseName("IX_SystemConfiguration_ConfigKey");

                    b.HasIndex("ConfigSection", "IsActive")
                        .HasDatabaseName("IX_SystemConfiguration_Section_Active");

                    b.ToTable("SystemConfiguration", null, t =>
                        {
                            t.HasCheckConstraint("CK_SystemConfiguration_Section", "ConfigSection IN ('Email', 'ActionReminderService', 'General', 'System')");
                        });
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.Configuration.SystemConfigurationAudit", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ChangedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuditId");

                    b.HasIndex("ChangedDate")
                        .HasDatabaseName("IX_SystemConfigurationAudit_ChangedDate");

                    b.HasIndex("ConfigurationId")
                        .HasDatabaseName("IX_SystemConfigurationAudit_ConfigId");

                    b.ToTable("SystemConfigurationAudit", (string)null);
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.CounterParty", b =>
                {
                    b.Property<int>("CounterPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CounterPartyId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AffiliatedTo")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CounterPartyNoAlpha")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<bool>("DisplayAtCheckIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("Since")
                        .HasColumnType("datetime");

                    b.HasKey("CounterPartyId")
                        .HasName("PK__CounterParty__3B75D760");

                    b.HasIndex("Country");

                    b.HasIndex(new[] { "CounterPartyNoAlpha" }, "COUNTERPARTY_NOA_IDX");

                    b.HasIndex(new[] { "Since" }, "COUNTERPARTY_SNC_IDX");

                    b.ToTable("CounterParty");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.Country", b =>
                {
                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.HasKey("CountryCode")
                        .HasName("PK__Country__5D9B0D2D34531A97");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.Currency", b =>
                {
                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<int>("DecimalPlaces")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.HasKey("CurrencyCode")
                        .HasName("PK__Currency__408426BEA95ECF99");

                    b.ToTable("Currency");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.DocuScanUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsSuperUser")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogon")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("UserIdentifier")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId")
                        .HasName("DOCUSCANUSER_PK");

                    b.HasIndex(new[] { "IsSuperUser" }, "IX_DocuScanUser_IsSuperUser");

                    b.HasIndex(new[] { "LastLogon" }, "IX_DocuScanUser_LastLogon");

                    b.HasIndex(new[] { "AccountName" }, "UK_DocuScanUser_AccountName")
                        .IsUnique();

                    b.HasIndex(new[] { "UserIdentifier" }, "UK_DocuScanUser_UserIdentifier")
                        .IsUnique();

                    b.ToTable("DocuScanUser");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ActionDescription")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("AssociatedToAppendix")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AssociatedToPua")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("AssociatedToPUA");

                    b.Property<string>("Authorisation")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("BankConfirmation")
                        .HasColumnType("bit");

                    b.Property<int>("BarCode")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("Confidential")
                        .HasColumnType("bit");

                    b.Property<int?>("CounterPartyId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("char(3)")
                        .IsFixedLength();

                    b.Property<DateTime?>("DateOfContract")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DispatchDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("DocumentNameId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentNo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("DtId")
                        .HasColumnType("int")
                        .HasColumnName("DT_ID");

                    b.Property<bool?>("Fax")
                        .HasColumnType("bit");

                    b.Property<int?>("FileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ForwardedToSignatoriesDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("OriginalReceived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReceivingDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ReminderGroup")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("SendingOutDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ThirdParty")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ThirdPartyId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("TranslatedVersionReceived")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime");

                    b.Property<string>("VersionNo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("DOCUMENT_PK");

                    b.HasIndex("CounterPartyId");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("DocumentNameId");

                    b.HasIndex("DtId");

                    b.HasIndex("FileId");

                    b.HasIndex(new[] { "BarCode" }, "uk_document_barcode")
                        .IsUnique();

                    b.ToTable("Document");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.DocumentFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Bytes")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(900)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue(".pdf");

                    b.HasKey("Id")
                        .HasName("DOCUMENTFILE_PK");

                    b.HasIndex(new[] { "FileName" }, "uk_file_filename")
                        .IsUnique();

                    b.ToTable("DocumentFile");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.DocumentName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__DocumentName__47DBAE45");

                    b.HasIndex("DocumentTypeId");

                    b.ToTable("DocumentName");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.DocumentType", b =>
                {
                    b.Property<int>("DtId")
                        .HasColumnType("int")
                        .HasColumnName("DT_ID");

                    b.Property<string>("ActionDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("O")
                        .IsFixedLength();

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("O")
                        .IsFixedLength();

                    b.Property<string>("Amount")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N")
                        .IsFixedLength();

                    b.Property<string>("AssociatedToAppendix")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N")
                        .IsFixedLength();

                    b.Property<string>("AssociatedToPua")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N")
                        .HasColumnName("AssociatedToPUA")
                        .IsFixedLength();

                    b.Property<string>("Authorisation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N")
                        .IsFixedLength();

                    b.Property<string>("BankConfirmation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N")
                        .IsFixedLength();

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("M")
                        .IsFixedLength();

                    b.Property<string>("Comment")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("O")
                        .IsFixedLength();

                    b.Property<string>("Confidential")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("M")
                        .IsFixedLength();

                    b.Property<string>("CounterParty")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("M")
                        .IsFixedLength();

                    b.Property<string>("CounterPartyAlpha")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("M")
                        .IsFixedLength();

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N")
                        .IsFixedLength();

                    b.Property<string>("DateOfContract")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("M")
                        .IsFixedLength();

                    b.Property<string>("DispatchDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("M")
                        .IsFixedLength();

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N")
                        .IsFixedLength();

                    b.Property<string>("DtName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DT_Name");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("M")
                        .IsFixedLength();

                    b.Property<string>("ForwardedToSignatoriesDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("O")
                        .IsFixedLength();

                    b.Property<bool>("IsAppendix")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("OriginalReceived")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("M")
                        .IsFixedLength();

                    b.Property<string>("ReceivingDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("M")
                        .IsFixedLength();

                    b.Property<string>("ReminderGroup")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("O")
                        .IsFixedLength();

                    b.Property<string>("SendingOutDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("O")
                        .IsFixedLength();

                    b.Property<string>("TranslatedVersionReceived")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("M")
                        .IsFixedLength();

                    b.Property<string>("ValidUntil")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N")
                        .IsFixedLength();

                    b.Property<string>("VersionNo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasDefaultValue("N")
                        .IsFixedLength();

                    b.HasKey("DtId")
                        .HasName("PK__Document__148CEA33753529D2");

                    b.ToTable("DocumentType");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CounterPartyId")
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .IsFixedLength();

                    b.Property<int?>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("USERACCOUNT_PK");

                    b.HasIndex("CounterPartyId");

                    b.HasIndex("CountryCode");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex(new[] { "UserId" }, "IX_UserPermissions_UserId");

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.Configuration.EmailRecipient", b =>
                {
                    b.HasOne("IkeaDocuScan.Infrastructure.Entities.Configuration.EmailRecipientGroup", "Group")
                        .WithMany("Recipients")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmailRecipient_Group");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.Configuration.SystemConfigurationAudit", b =>
                {
                    b.HasOne("IkeaDocuScan.Infrastructure.Entities.Configuration.SystemConfiguration", "Configuration")
                        .WithMany("AuditTrail")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ConfigAudit_Config");

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.CounterParty", b =>
                {
                    b.HasOne("IkeaDocuScan.Infrastructure.Entities.Country", "CountryNavigation")
                        .WithMany("CounterParties")
                        .HasForeignKey("Country")
                        .IsRequired()
                        .HasConstraintName("FK__CounterPa__Count__3D5E1FD2");

                    b.Navigation("CountryNavigation");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.Document", b =>
                {
                    b.HasOne("IkeaDocuScan.Infrastructure.Entities.CounterParty", "CounterParty")
                        .WithMany("Documents")
                        .HasForeignKey("CounterPartyId")
                        .HasConstraintName("FK__Document__Counte__5EBF139D");

                    b.HasOne("IkeaDocuScan.Infrastructure.Entities.Currency", "CurrencyCodeNavigation")
                        .WithMany("Documents")
                        .HasForeignKey("CurrencyCode")
                        .HasConstraintName("FK__Document__Curren__619B8048");

                    b.HasOne("IkeaDocuScan.Infrastructure.Entities.DocumentName", "DocumentName")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentNameId")
                        .HasConstraintName("FK__Document__Docume__5FB337D6");

                    b.HasOne("IkeaDocuScan.Infrastructure.Entities.DocumentType", "Dt")
                        .WithMany("Documents")
                        .HasForeignKey("DtId")
                        .HasConstraintName("FK__Document__DT_ID__6383C8BA");

                    b.HasOne("IkeaDocuScan.Infrastructure.Entities.DocumentFile", "File")
                        .WithMany("Documents")
                        .HasForeignKey("FileId")
                        .HasConstraintName("FK__Document__FileId__5AEE82B9");

                    b.Navigation("CounterParty");

                    b.Navigation("CurrencyCodeNavigation");

                    b.Navigation("DocumentName");

                    b.Navigation("Dt");

                    b.Navigation("File");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.DocumentName", b =>
                {
                    b.HasOne("IkeaDocuScan.Infrastructure.Entities.DocumentType", "DocumentType")
                        .WithMany("DocumentNames")
                        .HasForeignKey("DocumentTypeId")
                        .HasConstraintName("FK__DocumentN__Docum__48CFD27E");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.UserPermission", b =>
                {
                    b.HasOne("IkeaDocuScan.Infrastructure.Entities.CounterParty", "CounterParty")
                        .WithMany("UserPermissions")
                        .HasForeignKey("CounterPartyId")
                        .HasConstraintName("FK__UserPermi__Count__6A30C649");

                    b.HasOne("IkeaDocuScan.Infrastructure.Entities.Country", "CountryCodeNavigation")
                        .WithMany("UserPermissions")
                        .HasForeignKey("CountryCode")
                        .HasConstraintName("FK__UserPermi__Count__693CA210");

                    b.HasOne("IkeaDocuScan.Infrastructure.Entities.DocumentType", "DocumentType")
                        .WithMany("UserPermissions")
                        .HasForeignKey("DocumentTypeId")
                        .HasConstraintName("FK__UserPermi__Docum__6A30C649");

                    b.HasOne("IkeaDocuScan.Infrastructure.Entities.DocuScanUser", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserPermissions_DocuScanUser");

                    b.Navigation("CounterParty");

                    b.Navigation("CountryCodeNavigation");

                    b.Navigation("DocumentType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.Configuration.EmailRecipientGroup", b =>
                {
                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.Configuration.SystemConfiguration", b =>
                {
                    b.Navigation("AuditTrail");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.CounterParty", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.Country", b =>
                {
                    b.Navigation("CounterParties");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.Currency", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.DocuScanUser", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.DocumentFile", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.DocumentName", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("IkeaDocuScan.Infrastructure.Entities.DocumentType", b =>
                {
                    b.Navigation("DocumentNames");

                    b.Navigation("Documents");

                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
